"use client";

import React, { useState } from "react";
import { AnalysisResult } from "@/lib/ai-analyzer";
import { Copy, Check, Download, Mail, X, ShieldAlert } from "lucide-react";

interface ExportReportModalProps {
  analysis: AnalysisResult;
  isOpen: boolean;
  onClose: () => void;
}

export function ExportReportModal({ analysis, isOpen, onClose }: ExportReportModalProps) {
  const [copiedType, setCopiedType] = useState<string | null>(null);

  if (!isOpen) return null;

  const plainEnglishSummaryText = `🛡️ VIGILPHISH THREAT ASSESSMENT REPORT
Risk Score: ${analysis.riskScore}/100 [${analysis.riskLevel.toUpperCase()}]
Recommendation: ${analysis.recommendationAction}

Summary:
${analysis.aiSummary}

Key Threat Factors:
${analysis.threatFactors.map((f) => `• ${f.title} (${f.severity.toUpperCase()}): ${f.explanation}`).join("\n")}

Generated by VigilPhish AI & Live Threat Intelligence`;

  const itForwardTemplateText = `Subject: [SUSPICIOUS EMAIL / PHISH ALERT] Analysis Report (${analysis.riskScore}/100 Risk Score)

Hello Security / IT Operations Team,

I received a suspicious message and ran it through VigilPhish security analysis.

Risk Score: ${analysis.riskScore}/100
Verdict: ${analysis.riskLevel.toUpperCase()}
Target Brand Impersonated: ${analysis.targetBrand || "Unknown"}
Extracted Domains: ${analysis.extractedDomains.join(", ") || "None"}

AI Assessment:
${analysis.aiSummary}

Report Identifier: ${analysis.reportId}

Please advise if any domain blocks or firewall rules are needed.
Thank you.`;

  const handleCopy = (text: string, type: string) => {
    navigator.clipboard.writeText(text);
    setCopiedType(type);
    setTimeout(() => setCopiedType(null), 2500);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm">
      <div className="bg-slate-900 border border-slate-700 rounded-2xl w-full max-w-2xl overflow-hidden shadow-2xl flex flex-col max-h-[90vh]">
        {/* Header */}
        <div className="p-4 sm:p-5 border-b border-slate-800 flex items-center justify-between bg-slate-950">
          <div className="flex items-center gap-2.5">
            <ShieldAlert className="w-5 h-5 text-cyan-400" />
            <h2 className="text-base sm:text-lg font-bold text-white">Export Threat Report</h2>
          </div>
          <button
            onClick={onClose}
            className="text-slate-400 hover:text-white p-1 rounded-lg hover:bg-slate-800 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content */}
        <div className="p-4 sm:p-6 overflow-y-auto space-y-5 text-sm">
          {/* 1-Click Plain-English Copy */}
          <div className="border border-slate-800 rounded-xl p-3.5 bg-slate-950/60">
            <div className="flex items-center justify-between mb-2">
              <span className="font-semibold text-slate-200 text-xs uppercase tracking-wider">
                Plain-English Summary (For Slack / Friends / Family)
              </span>
              <button
                onClick={() => handleCopy(plainEnglishSummaryText, "summary")}
                className="text-cyan-400 hover:text-cyan-300 text-xs font-semibold flex items-center gap-1"
              >
                {copiedType === "summary" ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                {copiedType === "summary" ? "Copied to Clipboard" : "Copy Text"}
              </button>
            </div>
            <pre className="text-xs text-slate-300 font-sans whitespace-pre-wrap bg-slate-900 p-2.5 rounded border border-slate-800 max-h-36 overflow-y-auto">
              {plainEnglishSummaryText}
            </pre>
          </div>

          {/* IT Forward Template */}
          <div className="border border-slate-800 rounded-xl p-3.5 bg-slate-950/60">
            <div className="flex items-center justify-between mb-2">
              <span className="font-semibold text-slate-200 text-xs uppercase tracking-wider flex items-center gap-1.5">
                <Mail className="w-3.5 h-3.5 text-amber-400" /> IT Security Team Forward Template
              </span>
              <button
                onClick={() => handleCopy(itForwardTemplateText, "it")}
                className="text-amber-400 hover:text-amber-300 text-xs font-semibold flex items-center gap-1"
              >
                {copiedType === "it" ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                {copiedType === "it" ? "Copied Template" : "Copy Template"}
              </button>
            </div>
            <pre className="text-xs text-slate-300 font-mono whitespace-pre-wrap bg-slate-900 p-2.5 rounded border border-slate-800 max-h-32 overflow-y-auto">
              {itForwardTemplateText}
            </pre>
          </div>
        </div>

        {/* Footer Actions */}
        <div className="p-4 bg-slate-950 border-t border-slate-800 flex items-center justify-between">
          <span className="text-xs text-slate-400">Zero message text saved</span>
          <div className="flex items-center gap-2">
            <button
              onClick={handlePrint}
              className="bg-slate-800 hover:bg-slate-700 text-white text-xs font-semibold px-4 py-2 rounded-lg flex items-center gap-1.5 border border-slate-700 transition-colors"
            >
              <Download className="w-3.5 h-3.5" /> Print / Save PDF
            </button>
            <button
              onClick={onClose}
              className="bg-cyan-500 hover:bg-cyan-400 text-slate-950 text-xs font-bold px-4 py-2 rounded-lg transition-colors"
            >
              Done
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
